# Generated by Django 4.0.1 on 2022-02-01 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_otpmodel_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpmodel',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
