# Generated by Django 4.0.1 on 2022-02-01 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_otpmodel_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpmodel',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
